/**
 * Image Bank Metadata — maps each image file to its keywords
 * Used for smart matching: article tags/keyTerms → best matching image
 * 
 * Format: { "category": { "filename": ["keyword1", "keyword2", ...] } }
 */

const IMAGE_METADATA: Record<string, Record<string, string[]>> = {
    polity: {
        "polity-01.jpg": ["parliament", "building", "lok sabha", "rajya sabha", "new delhi", "legislature"],
        "polity-02.jpg": ["supreme court", "judiciary", "judgment", "bench", "constitution", "law"],
        "polity-03.jpg": ["constitution", "preamble", "fundamental rights", "directive principles"],
        "polity-04.jpg": ["election", "voting", "ballot", "evm", "polling", "booth"],
        "polity-05.jpg": ["rajya sabha", "parliament", "upper house", "council of states"],
        "polity-06.jpg": ["lok sabha", "parliament", "lower house", "house of people"],
        "polity-07.jpg": ["flag", "tricolor", "national", "tiranga", "independence"],
        "polity-08.jpg": ["president", "rashtrapati bhavan", "head of state", "executive"],
        "polity-09.jpg": ["high court", "judiciary", "state", "judicial review"],
        "polity-10.jpg": ["parliament", "democracy", "debate", "session", "bill"],
        "polity-11.jpg": ["election commission", "eci", "free fair election", "model code"],
        "polity-12.jpg": ["voting", "booth", "ballot", "polling station", "evm"],
        "polity-13.jpg": ["judiciary", "law", "justice", "court", "legal", "bench"],
        "polity-14.jpg": ["constitutional", "assembly", "drafting", "founding fathers"],
        "polity-15.jpg": ["governor", "raj bhavan", "state head", "appointment"],
        "polity-16.jpg": ["state legislature", "assembly", "vidhan sabha", "state"],
        "polity-17.jpg": ["panchayat", "raj", "village", "local governance", "73rd amendment"],
        "polity-18.jpg": ["municipal", "corporation", "urban", "city governance", "74th amendment"],
        "polity-19.jpg": ["political", "rally", "campaign", "party", "manifesto"],
        "polity-20.jpg": ["democracy", "people", "citizens", "participation", "republic"],
    },
    governance: {
        "governance-01.jpg": ["government", "office", "bureaucracy", "administration", "ias"],
        "governance-02.jpg": ["digital india", "technology", "e-governance", "online", "app"],
        "governance-03.jpg": ["aadhaar", "identity", "biometric", "uid", "card"],
        "governance-04.jpg": ["smart city", "urban", "development", "infrastructure"],
        "governance-05.jpg": ["bureaucracy", "office", "file", "official", "ias"],
        "governance-06.jpg": ["public service", "civil servant", "delivery", "citizen"],
        "governance-07.jpg": ["e-governance", "digital", "portal", "online service"],
        "governance-08.jpg": ["swachh bharat", "clean india", "sanitation", "toilet", "hygiene"],
        "governance-09.jpg": ["make in india", "manufacturing", "industry", "production"],
        "governance-10.jpg": ["jan dhan", "bank account", "financial inclusion", "banking"],
        "governance-11.jpg": ["police", "station", "law enforcement", "crime", "fir"],
        "governance-12.jpg": ["railway", "train", "transport", "irctc", "station"],
        "governance-13.jpg": ["ration", "pds", "food", "distribution", "subsidy"],
        "governance-14.jpg": ["pension", "elderly", "senior citizen", "social security"],
        "governance-15.jpg": ["health", "hospital", "ayushman bharat", "medical", "healthcare"],
        "governance-16.jpg": ["skill", "development", "training", "vocational", "employment"],
        "governance-17.jpg": ["urban", "development", "city", "town planning", "metro"],
        "governance-18.jpg": ["rural", "development", "village", "gram", "mgnrega"],
        "governance-19.jpg": ["infrastructure", "highway", "road", "bridge", "construction"],
        "governance-20.jpg": ["welfare", "scheme", "benefit", "subsidy", "transfer", "dbt"],
    },
    economy: {
        "economy-01.jpg": ["rbi", "reserve bank", "monetary", "central bank", "governor"],
        "economy-02.jpg": ["rupee", "currency", "forex", "exchange rate", "money"],
        "economy-03.jpg": ["stock market", "sensex", "nifty", "shares", "trading", "bse"],
        "economy-04.jpg": ["banking", "finance", "bank", "loan", "credit", "npa"],
        "economy-05.jpg": ["gst", "tax", "indirect tax", "revenue", "collection"],
        "economy-06.jpg": ["budget", "finance ministry", "fiscal", "expenditure", "deficit"],
        "economy-07.jpg": ["economy", "growth", "gdp", "development", "progress"],
        "economy-08.jpg": ["export", "import", "trade", "container", "port", "shipping"],
        "economy-09.jpg": ["startup", "business", "entrepreneur", "innovation", "unicorn"],
        "economy-10.jpg": ["microfinance", "self help group", "shg", "women", "micro credit"],
        "economy-11.jpg": ["insurance", "policy", "lic", "coverage", "premium"],
        "economy-12.jpg": ["inflation", "price", "cpi", "wpi", "cost", "expensive"],
        "economy-13.jpg": ["coal", "mining", "mineral", "extraction", "energy"],
        "economy-14.jpg": ["steel", "industry", "metal", "manufacturing", "production"],
        "economy-15.jpg": ["textile", "fabric", "garment", "clothing", "cotton"],
        "economy-16.jpg": ["oil", "refinery", "petroleum", "crude", "fuel", "gas"],
        "economy-17.jpg": ["solar", "energy", "renewable", "panel", "green energy"],
        "economy-18.jpg": ["wind", "energy", "turbine", "renewable", "power"],
        "economy-19.jpg": ["cryptocurrency", "digital", "blockchain", "bitcoin", "fintech"],
        "economy-20.jpg": ["msme", "small business", "enterprise", "sme", "cottage"],
        "economy-21.jpg": ["fdi", "foreign investment", "fii", "capital", "investor"],
        "economy-22.jpg": ["gdp", "economic growth", "national income", "statistics"],
        "economy-23.jpg": ["poverty", "rural", "bpl", "inequality", "poor"],
    },
    ir: {
        "ir-01.jpg": ["united nations", "un", "general assembly", "unga", "multilateral"],
        "ir-02.jpg": ["diplomacy", "handshake", "bilateral", "foreign affairs", "summit"],
        "ir-03.jpg": ["india china", "border", "lac", "galwan", "doklam", "tibet"],
        "ir-04.jpg": ["indo pacific", "ocean", "quad", "maritime", "sea"],
        "ir-05.jpg": ["g20", "summit", "leaders", "multilateral", "global"],
        "ir-06.jpg": ["brics", "summit", "emerging", "brazil russia", "south africa"],
        "ir-07.jpg": ["india usa", "america", "bilateral", "strategic", "partnership"],
        "ir-08.jpg": ["india russia", "bilateral", "defense", "strategic"],
        "ir-09.jpg": ["saarc", "south asia", "regional", "cooperation", "neighbour"],
        "ir-10.jpg": ["asean", "southeast asia", "act east", "partnership", "summit"],
        "ir-11.jpg": ["wto", "world trade", "trade dispute", "tariff", "dumping"],
        "ir-12.jpg": ["nuclear", "deal", "agreement", "nonproliferation", "npt", "treaty"],
        "ir-13.jpg": ["refugee", "migration", "crisis", "displacement", "asylum"],
        "ir-14.jpg": ["peacekeeping", "un", "blue helmet", "mission", "conflict"],
        "ir-15.jpg": ["sanctions", "trade war", "embargo", "restriction"],
        "ir-16.jpg": ["middle east", "conflict", "war", "israel", "palestine", "iran"],
        "ir-17.jpg": ["climate", "summit", "paris", "cop", "emission", "agreement"],
        "ir-18.jpg": ["world bank", "development", "aid", "loan", "ibrd"],
        "ir-19.jpg": ["imf", "international monetary fund", "bailout", "sdr"],
        "ir-20.jpg": ["bilateral", "treaty", "signing", "mou", "agreement", "pact"],
    },
    environment: {
        "environment-01.jpg": ["forest", "tiger", "wildlife", "jungle", "national park"],
        "environment-02.jpg": ["wildlife", "sanctuary", "animal", "conservation", "biodiversity"],
        "environment-03.jpg": ["river", "ganges", "ganga", "water", "pollution", "clean"],
        "environment-04.jpg": ["air pollution", "smog", "delhi", "aqi", "pm2.5", "particulate"],
        "environment-05.jpg": ["coral", "reef", "ocean", "marine", "bleaching"],
        "environment-06.jpg": ["himalaya", "glacier", "mountain", "snow", "melting", "climate"],
        "environment-07.jpg": ["mangrove", "sundarbans", "coastal", "wetland", "ecosystem"],
        "environment-08.jpg": ["solar", "panel", "renewable", "green", "clean energy"],
        "environment-09.jpg": ["deforestation", "logging", "trees", "forest loss"],
        "environment-10.jpg": ["electric vehicle", "ev", "green transport", "battery"],
        "environment-11.jpg": ["plastic", "pollution", "ocean", "waste", "microplastic"],
        "environment-12.jpg": ["biodiversity", "ecosystem", "nature", "species"],
        "environment-13.jpg": ["wetland", "birds", "sanctuary", "ramsar", "migratory"],
        "environment-14.jpg": ["drought", "dry", "arid", "scarcity", "famine"],
        "environment-15.jpg": ["rainforest", "tropical", "canopy", "dense forest"],
        "environment-16.jpg": ["endangered", "species", "wildlife", "iucn", "red list"],
        "environment-17.jpg": ["climate change", "global warming", "carbon", "greenhouse"],
        "environment-18.jpg": ["water", "scarcity", "well", "groundwater", "drinking"],
        "environment-19.jpg": ["waste", "management", "recycling", "swm", "composting"],
        "environment-20.jpg": ["national park", "protected area", "conservation", "reserve"],
    },
    science: {
        "science-01.jpg": ["isro", "rocket", "launch", "pslv", "gslv", "satellite"],
        "science-02.jpg": ["space", "satellite", "orbit", "communication", "remote sensing"],
        "science-03.jpg": ["artificial intelligence", "ai", "robot", "machine learning", "chatbot"],
        "science-04.jpg": ["quantum", "computing", "qubit", "technology", "processor"],
        "science-05.jpg": ["5g", "telecom", "tower", "spectrum", "broadband", "network"],
        "science-06.jpg": ["biotechnology", "dna", "lab", "genome", "crispr", "gene"],
        "science-07.jpg": ["nuclear", "reactor", "energy", "atomic", "power plant"],
        "science-08.jpg": ["supercomputer", "data center", "hpc", "computing", "server"],
        "science-09.jpg": ["drone", "uav", "unmanned", "aerial", "surveillance"],
        "science-10.jpg": ["nanotechnology", "microscope", "research", "nanomaterial"],
        "science-11.jpg": ["cybersecurity", "hacking", "computer", "data breach", "malware"],
        "science-12.jpg": ["mars", "mission", "space exploration", "planet", "mangalyaan"],
        "science-13.jpg": ["chandrayaan", "moon", "lunar", "lander", "rover"],
        "science-14.jpg": ["blockchain", "digital", "crypto", "ledger", "decentralized"],
        "science-15.jpg": ["semiconductor", "chip", "circuit", "processor", "fab"],
        "science-16.jpg": ["electric car", "ev", "battery", "charging", "green"],
        "science-17.jpg": ["3d printing", "manufacturing", "additive", "prototype"],
        "science-18.jpg": ["internet of things", "iot", "smart", "connected", "sensor"],
        "science-19.jpg": ["green hydrogen", "fuel cell", "clean energy", "electrolyzer"],
        "science-20.jpg": ["telescope", "astronomy", "stars", "observatory", "space"],
    },
    social: {
        "social-01.jpg": ["education", "school", "children", "learning", "classroom"],
        "social-02.jpg": ["women", "empowerment", "gender", "female", "girl"],
        "social-03.jpg": ["healthcare", "hospital", "doctor", "patient", "medical"],
        "social-04.jpg": ["tribal", "adivasi", "indigenous", "schedule tribe", "forest"],
        "social-05.jpg": ["child labour", "exploitation", "minor", "work", "children"],
        "social-06.jpg": ["caste", "discrimination", "social justice", "dalit", "reservation"],
        "social-07.jpg": ["elderly", "pension", "old age", "senior", "retirement"],
        "social-08.jpg": ["disability", "rights", "wheelchair", "accessibility", "pwda"],
        "social-09.jpg": ["migration", "workers", "labor", "migrant", "displacement"],
        "social-10.jpg": ["unemployment", "youth", "job", "employment", "skill gap"],
        "social-11.jpg": ["literacy", "reading", "books", "education", "adult"],
        "social-12.jpg": ["vaccination", "health", "child", "immunization", "polio"],
        "social-13.jpg": ["sanitation", "toilet", "clean", "hygiene", "swachh"],
        "social-14.jpg": ["nutrition", "midday meal", "food", "malnutrition", "hunger"],
        "social-15.jpg": ["gender equality", "women", "feminism", "equal rights"],
        "social-16.jpg": ["domestic violence", "awareness", "abuse", "protection"],
        "social-17.jpg": ["ngo", "volunteer", "service", "civil society", "charity"],
        "social-18.jpg": ["slum", "urban poverty", "housing", "informal settlement"],
        "social-19.jpg": ["mental health", "awareness", "depression", "stress", "wellbeing"],
        "social-20.jpg": ["population", "density", "demographic", "census", "growth"],
    },
    security: {
        "security-01.jpg": ["army", "soldier", "military", "defense", "infantry"],
        "security-02.jpg": ["border", "bsf", "fencing", "patrol", "security force"],
        "security-03.jpg": ["navy", "warship", "maritime", "sea", "fleet", "vessel"],
        "security-04.jpg": ["air force", "fighter jet", "aircraft", "iaf", "rafale"],
        "security-05.jpg": ["crpf", "paramilitary", "internal security", "deployment"],
        "security-06.jpg": ["naxal", "insurgency", "lwe", "maoist", "red corridor"],
        "security-07.jpg": ["cybersecurity", "cyber threat", "digital", "hacking", "data"],
        "security-08.jpg": ["surveillance", "cctv", "camera", "monitoring", "watch"],
        "security-09.jpg": ["terrorism", "security", "alert", "anti terror", "nia"],
        "security-10.jpg": ["coast guard", "patrol", "maritime", "sea", "piracy"],
        "security-11.jpg": ["radar", "defense", "detection", "air defense", "system"],
        "security-12.jpg": ["missile", "defense", "ballistic", "agni", "prithvi", "brahmos"],
        "security-13.jpg": ["intelligence", "agency", "raw", "ib", "espionage"],
        "security-14.jpg": ["drug", "trafficking", "narcotics", "ncb", "seizure"],
        "security-15.jpg": ["border fencing", "barbed wire", "loc", "boundary"],
        "security-16.jpg": ["riot", "police", "law and order", "crowd", "teargas"],
        "security-17.jpg": ["ammunition", "weapons", "arms", "firearm", "defense"],
        "security-18.jpg": ["helicopter", "military", "rescue", "operation", "airlift"],
        "security-19.jpg": ["commando", "special forces", "nsg", "para sf"],
        "security-20.jpg": ["ceasefire", "peace", "border", "truce", "dialogue"],
    },
    agriculture: {
        "agriculture-01.jpg": ["farmer", "paddy", "rice", "field", "cultivation"],
        "agriculture-02.jpg": ["wheat", "harvest", "golden", "rabi", "crop"],
        "agriculture-03.jpg": ["tractor", "farming", "mechanization", "equipment"],
        "agriculture-04.jpg": ["irrigation", "canal", "water", "dam", "command area"],
        "agriculture-05.jpg": ["organic", "farming", "vegetable", "natural", "pesticide free"],
        "agriculture-06.jpg": ["mandi", "market", "apmc", "produce", "trade", "msp"],
        "agriculture-07.jpg": ["dairy", "cow", "milk", "cattle", "livestock", "amul"],
        "agriculture-08.jpg": ["fishery", "fishing", "boat", "aquaculture", "marine"],
        "agriculture-09.jpg": ["sugarcane", "sugar", "ethanol", "crop", "field"],
        "agriculture-10.jpg": ["cotton", "harvest", "bt cotton", "textile", "fibre"],
        "agriculture-11.jpg": ["fertilizer", "farm", "soil", "urea", "dap", "subsidy", "dbt"],
        "agriculture-12.jpg": ["crop insurance", "pmfby", "coverage", "protection"],
        "agriculture-13.jpg": ["seed", "planting", "sowing", "germination", "kharif"],
        "agriculture-14.jpg": ["greenhouse", "horticulture", "plants", "nursery", "floriculture"],
        "agriculture-15.jpg": ["drip irrigation", "micro", "water saving", "efficient"],
        "agriculture-16.jpg": ["cold storage", "warehouse", "godown", "supply chain"],
        "agriculture-17.jpg": ["food processing", "factory", "value addition", "fpo"],
        "agriculture-18.jpg": ["sericulture", "silk", "worm", "cocoon", "textile"],
        "agriculture-19.jpg": ["tea", "plantation", "assam", "darjeeling", "estate"],
        "agriculture-20.jpg": ["spice", "plantation", "kerala", "cardamom", "pepper"],
    },
    history: {
        "history-01.jpg": ["taj mahal", "agra", "mughal", "shah jahan", "monument"],
        "history-02.jpg": ["red fort", "delhi", "mughal", "independence", "lal qila"],
        "history-03.jpg": ["qutub minar", "delhi", "sultanate", "tower", "medieval"],
        "history-04.jpg": ["ajanta", "ellora", "caves", "buddhist", "rock cut", "painting"],
        "history-05.jpg": ["hampi", "ruins", "vijayanagara", "karnataka", "empire"],
        "history-06.jpg": ["konark", "sun temple", "odisha", "architecture", "wheel"],
        "history-07.jpg": ["khajuraho", "temple", "sculpture", "madhya pradesh", "chandela"],
        "history-08.jpg": ["mahabodhi", "bodh gaya", "buddha", "enlightenment", "temple"],
        "history-09.jpg": ["golden temple", "amritsar", "sikh", "gurdwara", "harmandir"],
        "history-10.jpg": ["classical dance", "bharatanatyam", "kathak", "odissi", "culture"],
        "history-11.jpg": ["republic day", "parade", "january", "national", "celebration"],
        "history-12.jpg": ["independence day", "tricolor", "august", "freedom", "national"],
        "history-13.jpg": ["yoga", "meditation", "spiritual", "wellness", "international yoga day"],
        "history-14.jpg": ["music", "sitar", "classical", "raga", "concert", "cultural"],
        "history-15.jpg": ["rangoli", "festival", "diwali", "art", "decoration", "celebration"],
        "history-16.jpg": ["meenakshi", "temple", "madurai", "dravidian", "tamil", "architecture"],
        "history-17.jpg": ["mughal", "architecture", "dome", "arch", "medieval", "empire"],
        "history-18.jpg": ["buddhist", "monastery", "ladakh", "lama", "himalayas"],
        "history-19.jpg": ["warli", "art", "tribal", "painting", "folk", "indigenous"],
        "history-20.jpg": ["handicraft", "pottery", "artisan", "traditional", "craft"],
    },
    geography: {
        "geography-01.jpg": ["himalaya", "mountain", "snow", "peak", "range", "everest"],
        "geography-02.jpg": ["indian ocean", "coast", "beach", "sea", "maritime"],
        "geography-03.jpg": ["western ghats", "forest", "biodiversity", "sahyadri"],
        "geography-04.jpg": ["thar", "desert", "rajasthan", "arid", "sand", "dune"],
        "geography-05.jpg": ["ganges", "river", "varanasi", "ghat", "holy", "plain"],
        "geography-06.jpg": ["deccan", "plateau", "landscape", "peninsular"],
        "geography-07.jpg": ["brahmaputra", "river", "assam", "northeast", "flood"],
        "geography-08.jpg": ["andaman", "nicobar", "island", "bay of bengal", "archipelago"],
        "geography-09.jpg": ["india map", "geography", "states", "boundary", "cartography"],
        "geography-10.jpg": ["monsoon", "rain", "southwest", "season", "precipitation"],
        "geography-11.jpg": ["earthquake", "seismic", "zone", "richter", "tectonic"],
        "geography-12.jpg": ["volcanic", "island", "barren", "eruption", "magma"],
        "geography-13.jpg": ["delta", "river", "sundarbans", "alluvial", "sediment"],
        "geography-14.jpg": ["coral island", "lakshadweep", "atoll", "lagoon"],
        "geography-15.jpg": ["northern plains", "punjab", "gangetic", "alluvial", "fertile"],
        "geography-16.jpg": ["kaveri", "river", "south", "karnataka", "tamil nadu", "dispute"],
        "geography-17.jpg": ["cyclone", "weather", "storm", "hurricane", "tropical"],
        "geography-18.jpg": ["glacier", "ice", "himalaya", "retreating", "meltwater"],
        "geography-19.jpg": ["soil", "types", "alluvial", "black", "laterite", "red"],
        "geography-20.jpg": ["peninsular", "india", "plateau", "landscape", "south"],
    },
    ethics: {
        "ethics-01.jpg": ["justice", "scales", "law", "fairness", "balance"],
        "ethics-02.jpg": ["gandhi", "nonviolence", "peace", "ahimsa", "mahatma"],
        "ethics-03.jpg": ["integrity", "honesty", "truth", "moral", "character"],
        "ethics-04.jpg": ["whistleblower", "transparency", "truth", "expose", "courage"],
        "ethics-05.jpg": ["corruption", "bribery", "money", "unethical", "scam"],
        "ethics-06.jpg": ["civil service", "duty", "officer", "ias", "public service"],
        "ethics-07.jpg": ["empathy", "compassion", "helping", "kindness", "care"],
        "ethics-08.jpg": ["accountability", "governance", "audit", "cag", "oversight"],
        "ethics-09.jpg": ["moral", "values", "ethics", "principled", "virtue"],
        "ethics-10.jpg": ["human rights", "dignity", "equality", "freedom", "rights"],
        "ethics-11.jpg": ["public servant", "officer", "governance", "service"],
        "ethics-12.jpg": ["lokpal", "ombudsman", "anti corruption", "lokayukta"],
        "ethics-13.jpg": ["rti", "information", "transparency", "right to know"],
        "ethics-14.jpg": ["diversity", "inclusion", "team", "pluralism", "unity"],
        "ethics-15.jpg": ["leadership", "guidance", "mentor", "inspire", "role model"],
    },
    disaster: {
        "disaster-01.jpg": ["flood", "rescue", "boat", "submerged", "waterlogging"],
        "disaster-02.jpg": ["earthquake", "damage", "rubble", "collapse", "seismic"],
        "disaster-03.jpg": ["cyclone", "storm", "coast", "wind", "damage", "landfall"],
        "disaster-04.jpg": ["landslide", "mountain", "debris", "slope", "rain"],
        "disaster-05.jpg": ["drought", "dry", "cracked earth", "famine", "water scarcity"],
        "disaster-06.jpg": ["tsunami", "wave", "coastal", "sea surge", "warning"],
        "disaster-07.jpg": ["forest fire", "wildfire", "blaze", "burn", "smoke"],
        "disaster-08.jpg": ["ndrf", "rescue", "team", "disaster response", "relief"],
        "disaster-09.jpg": ["relief camp", "shelter", "displaced", "humanitarian", "aid"],
        "disaster-10.jpg": ["flood damage", "village", "aftermath", "destruction"],
        "disaster-11.jpg": ["satellite", "weather", "hurricane", "imd", "forecast"],
        "disaster-12.jpg": ["evacuation", "people", "emergency", "flee", "safety"],
        "disaster-13.jpg": ["first aid", "medical", "rescue", "ambulance", "treatment"],
        "disaster-14.jpg": ["rebuilding", "reconstruction", "after disaster", "recovery"],
        "disaster-15.jpg": ["early warning", "system", "alert", "siren", "preparedness"],
    },
};

export default IMAGE_METADATA;
