#!/bin/bash
# ==============================================================================
# CURRENTIAS DAILY AUTOMATION SCRIPT
# This script runs the local ePaper pipeline and emails the PDF to the user.
#
# When run via launchd (com.currentias.epaper), stdout/stderr are automatically
# captured to automation_run.log and automation_error.log respectively.
# When run manually, output goes to the terminal AND is appended to the log file.
# ==============================================================================

# Ensure we are in the right directory
cd "/Users/mgtvalavan/UPSC coaching antigravity" || exit

# Load paths for Node/NPM if run via launchd/cron
export PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# Only attempt to use NVM if the path variable was configured inside ~/.nvm, otherwise the standard brew installation should be used
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Detect if running under launchd (stdout is already redirected to log file)
# If running manually from a terminal, tee output to the log file as well.
LOG_FILE="automation_run.log"
if [ -t 1 ]; then
    # Running interactively in a terminal — tee to log file
    exec > >(tee -a "$LOG_FILE") 2>&1
fi
# When run by launchd, stdout/stderr already go to the log files via the plist,
# so we just write to stdout normally — no double-write.

echo "=========================================================="
echo "Starting Daily CurrentIAS Generation at $(date)"

# Check if Next.js server is running
SERVER_STARTED_BY_SCRIPT=0
if curl -s -o /dev/null http://localhost:3000; then
    echo "Next.js server is already running on port 3000."
else
    echo "Starting Next.js server in the background..."
    # Using npx next dev directly helps avoid npm child process lingering issues
    npx next dev > next_server.log 2>&1 &
    NEXT_PID=$!
    SERVER_STARTED_BY_SCRIPT=1
    
    # Wait for the server to be ready
    echo "Waiting for Next.js server to be ready on port 3000..."
    for i in {1..30}; do
        if curl -s -o /dev/null http://localhost:3000; then
            echo "Next.js server is up."
            break
        fi
        sleep 2
    done
fi

echo "[1/6] Scraping news and generating Master Lead & Articles..."
npx tsx scripts/generate_custom_epaper.ts
GEN_EXIT=$?

if [ $GEN_EXIT -ne 0 ]; then
    echo "❌ ePaper generation failed — check logs for details."
    echo "Generation failed at $(date)" >> automation_error.log
    # Still try to continue if partial data exists
fi

echo "[2/6] Regenerating Quick Bytes with diversity-enforced prompt..."
npx tsx scripts/regenerate-quickbytes.ts
QB_EXIT=$?
if [ $QB_EXIT -ne 0 ]; then
    echo "⚠️ Quick Bytes regeneration failed — ePaper will use fallback/empty Quick Bytes."
    echo "Quick Bytes regen failed at $(date)" >> automation_error.log
fi

echo "[3/6] Generating front page extras (Quote, On This Day, Data Snapshot)..."
npx tsx scripts/generate-front-page-extras.ts
FPE_EXIT=$?
if [ $FPE_EXIT -ne 0 ]; then
    echo "⚠️ Front page extras generation failed — ePaper will have empty extras."
    echo "Front page extras failed at $(date)" >> automation_error.log
fi

echo "[4/6] Mocks already generated by AI pipeline..."

echo "[5/6] Running pre-send validation checklist..."
npx tsx scripts/validate_epaper.ts
VALIDATION_EXIT=$?

if [ $VALIDATION_EXIT -ne 0 ]; then
    echo "❌ VALIDATION FAILED — Skipping email send. Check automation_error.log for details."
    echo "Validation failed at $(date)" >> automation_error.log
else
    echo "[6/6] Validation passed! Generating PDF and sending email..."
    npx tsx scripts/test-email.ts
fi

# Cleanup Next.js server if we started it
if [ $SERVER_STARTED_BY_SCRIPT -eq 1 ]; then
    echo "Stopping Next.js server..."
    kill $NEXT_PID 2>/dev/null
    
    # Also explicitly kill the process listening on port 3000 just to be safe
    # If the kill above worked gracefully this is just a backup.
    lsof -ti:3000 | xargs kill -9 2>/dev/null
fi

echo "Daily automation complete at $(date)!"
